Adding two R notebook to examples repo
aodn/rimrep-examples pull request #7
Opened 2023-06-05 06:44 UTC by lidefi87

The first notebook [Extract_Water_Temp](https://github.com/lidefi87/rimrep-examples/blob/main/poc-data-api/Extracting_Water_Temperature_at_Site.md) uses the AIMS SST data and extracts data for points of interest. The second notebook, [Extract_Spatial_Data_GBR](https://github.com/lidefi87/rimrep-examples/blob/main/poc-data-api/Extracting_Spatial_Data_GBR_Features.md), extracts the spatial data for all GBR features in the Great Barrier Reef (GBR) Feature and creates a shapefile that can be saved locally.

There are two versions of each example script: the GitHub compatible version (ending in .md) and the RStudio friendly version (.Rmd). I have kept both because they may be useful to different users, but I should probably add some information about what each format is better for in the `README` file. But we can keep a single version if you think it is best.

2023-06-06 01:58 UTC, barbuz reviewed
The notebooks look great, nice job!

Would it be possible to have the generated maps show in the markdown notebooks? It would be nice as a way to show everything without requiring people to run the code themselves.

I have just a couple of notes about our datasets:
- You have used `UNIQUE_ID` for the gbr-features, but that's not actually the ID column of the dataset. I am not sure myself how exactly that dataset has been built, but it has multiple columns with "ID" in the name which all have some duplicate values and so cannot act as IDs for the rows. When no valid ID column is present in the dataset we will always add a new column `fid` with generated unique ID values, as we did in this case. I don't think you really use the value of the ID column here so it doesn't matter, I just wanted to let you know.
- The aims-sst dataset has two columns `lat` and `lon` that you could use instead of extracting this information from the geometry column. It's still good that you did that, to show people how they can manipulate geometries. In general, we will always have 4 columns with the minimum and maximum lat/lon (as we need them for pygeoapi), but for point geometries such as here, 2 columns are enough.

2023-06-06 02:35 UTC, lidefi87 commented
Thanks! I just added the figures to the notebooks. These will only show in the `.md` files though. Should I add a note in the `README` file explaining why we have two versions of these files?

About the IDs for the GBR features, I was a little confused myself, but I used the `UNIQUE_ID` field because it was the only one that matched the description of the unique code used by the GBRMPA (10-11 digits code). I kept the names because I thought it would be useful for some users. But, I will definitely create a new ID column if I ever need it.

About the AIMS SST data, should I use the `lat` and `lon` fields instead? I think I may have misunderstood you, I thought you wanted to use the `geometry` field. Looking at the datasets again, I think it was only for the GBR data. I can add the `lat` and `lon` option to this notebook, so people can see that they have two options to access the spatial data.

About the min and max coordinates, I can add this to the GBR example. I saw these fields, but did not access them as the `geometry` field had more detail.

2023-06-06 04:01 UTC, barbuz commented
> Should I add a note in the README file explaining why we have two versions of these files?

Yep, that would be nice!

> But, I will definitely create a new ID column if I ever need it.

You don't need to create a new ID column, I just meant that we've already done it and it's called `fid` in the dataset! 
I agree, getting the codes used by GBRMPA is going to be useful for some users, so I'm happy with the way the notebook does it now. 

> About the AIMS SST data, should I use the lat and lon fields instead? I think I may have misunderstood you, I thought you wanted to use the geometry field.

No, you are right, we want these notebooks to show how you can use the geometries included in the data. But the lat/lon (or min/max) columns can be much easier to use for some purposes. Where the geometries columns are really useful is when you want to plot the areas covered by the data (as you have done in the gbr-features notebook), or when you want to select data that is part of a certain region. 
We could think of an example where you select a specific reef from gbr-features, get its geometry, and use the geometry to filter the aims-sst data to keep only the points inside this reef. But we don't need to have all that in these notebooks, it can be the subject of a future one.

In short, maybe you could add a mention about how the same information in this case could be read from the lat/lon columns, but I think these notebooks are generally good to go.

2023-06-06 04:39 UTC, diodon commented
Great job Denisse!!! Very well documented. This is what we need, a narrative that explains the process in detail. 

Regarding the extraction of the data by site, this project has sites as the reef name where the loggers are deployed and sub-sites (also known as locations) which are the location on the reef. They normally deploy in the reef flat (<3m) and on the reef slope. If you explore the subsite name, you will find SL and FL. Maybe is a good idea to separate the calculation of the mean temperature by location

2023-06-06 04:42 UTC, diodon commented
Could you extend the GRB features notebook to use one of the geometries for one Reef and filter the AIMS temperature dataset to extract data inside the reef's polygon?

2023-06-06 06:10 UTC, lidefi87 commented
I updated the `README` with more information about the two markdown formats with the same name. 

> You don't need to create a new ID column, I just meant that we've already done it and it's called `fid` in the dataset! I agree, getting the codes used by GBRMPA is going to be useful for some users, so I'm happy with the way the notebook does it now.

Ah, I got it now. I did not notice there was a `fid` field in the GBR dataset too.

> In short, maybe you could add a mention about how the same information in this case could be read from the lat/lon columns, but I think these notebooks are generally good to go.

I have added this information to the AIMS notebook. I labelled them option 1 and 2 for site and coordinate extraction. Hopefully it is clear that this shows two different ways of obtaining the same information. If this is not clear, let me know and I will improve the text.

I will be working on @diodon comments now. I will keep you updated.

2023-06-06 07:03 UTC, lidefi87 commented
> Regarding the extraction of the data by site, this project has sites as the reef name where the loggers are deployed and sub-sites (also known as locations) which are the location on the reef. They normally deploy in the reef flat (<3m) and on the reef slope. If you explore the subsite name, you will find SL and FL. Maybe is a good idea to separate the calculation of the mean temperature by location

I am having trouble finding the field that contains this information. I looked through all fields and I could not find any classification containing SL/slope and FL/flat or depth. But there are two fields that may be relevant: `CLASS_CONF`, which has four classes ranging from low to high, and `UN_FEATURE`, which is a boolean field.

Yesterday, I tried to find this dataset in stac and pygeoapi, but I could not find it. I tried again today, but it seems that my password has been reset because the one in my password manager no longer works. I am waiting for an email to reset it, so I will not be able to check this until tomorrow.

2023-06-06 09:32 UTC, diodon commented
> > Regarding the extraction of the data by site, this project has sites as the reef name where the loggers are deployed and sub-sites (also known as locations) which are the location on the reef. They normally deploy in the reef flat (<3m) and on the reef slope. If you explore the subsite name, you will find SL and FL. Maybe is a good idea to separate the calculation of the mean temperature by location
> 
> I am having trouble finding the field that contains this information. I looked through all fields and I could not find any classification containing SL/slope and FL/flat or depth. But there are two fields that may be relevant: `CLASS_CONF`, which has four classes ranging from low to high, and `UN_FEATURE`, which is a boolean field.
> 
> Yesterday, I tried to find this dataset in stac and pygeoapi, but I could not find it, but I think I found the [source](https://eatlas.org.au/data/uuid/ac8e8e4f-fc0e-4a01-9c3d-f27e4a8fac3c). The fields described there do not have information about the deployment depth, but the two fields I highlighted above are not included in this website. It'd be great if I could get some finding the right field I should be using for this.

Sorry, there is no variable identifying the location. "FL" and "SL" (and some others too) are part of the subsite string: 

```
location$subsite[grepl("SL", location$subsite)]
  [1] "KIMSL1"            "LOWENDALSL1"       "LOWENDALSL1S"      "BRIDLEDSL1"        "VANSL1"            "LIMDSL1"           "LIMSL1"            "LIMVDSL1"          "TUARSL1"          
 [10] "RAISL1"            "SANSL1"            "SANDSL1"           "TYDSL1"            "NONAMESL1"         "MACGSL1"           "LIZSL1"            "COCSL1"            "BLASL1"           
 [19] "SNAPISSL1"         "LOWSL1"            "OPALSL1"           "AG1SL1"            "FRNKSL2"           "MCCULLSL1"         "SCOTT_SL4"         "CARSL1"            "IMPERIEUSEOUTSL1" 
 [28] "HIGHSL2"           "FITZSL2"           "THETSL1"           "ARLSL1"            "GRESL1"            "NBARSL1"           "DUNKSL1"           "TAYLORSL1"         "MYRSL1" 
```

So you need to parse the string and create a new variable (e.g. `location`)

2023-06-07 02:01 UTC, lidefi87 commented
> Regarding the extraction of the data by site, this project has sites as the reef name where the loggers are deployed and sub-sites (also known as locations) which are the location on the reef. They normally deploy in the reef flat (<3m) and on the reef slope. If you explore the subsite name, you will find SL and FL. Maybe is a good idea to separate the calculation of the mean temperature by location

I realised that I was looking at the wrong data, the GBR features instead of the AIMS temperature. This is now completed. But, I should point out that there were sites that did not have either of the deployment tags: `SL` or `FL`. I classified these as `NA`, but we can create a new category, perhaps `unknown` will be better. If you have a preference on how to classify this group with no deployment information, let me know and I will update this notebook.

2023-06-07 08:33 UTC, lidefi87 commented
> Could you extend the GRB features notebook to use one of the geometries for one Reef and filter the AIMS temperature dataset to extract data inside the reef's polygon? Maybe is better to make another notebook
> 
> Maybe in the form of a function that receives the reef name or the reef id and returns the polygon as an sf object that could be used as a boundary for filtering

This has now been completed. I created a few functions that allow users to select GBR features by name, ID or both. There is also a new notebook showing how this works.

I will not be off until next week. I will continue with the Python notebooks then.

2023-06-13 01:29 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +Connecting to the AIMS Sea Surface Temperature Monitoring Program. This can take a minute or so.
Connecting to the AIMS Sea Surface water temperature monitoring Program dataset

2023-06-13 02:53 UTC, diodon requested changes

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Spatial_Data_GBR_Features.Rmd
> +We can extract data from the AIMS dataset by using `dplyr` verbs as shown below.
AIMS Sea Surface Water Temperature dataset by using `dplyr` verbs as shown below. This could take few seconds up to one minute depending on your Internet connection speed.

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Spatial_Data_GBR_Features.Rmd
> +As explained above, the `geometry` field is in WKB format, which we will transform into degree coordinates in the next step. Here, we will use the `WKB` to transform the `geometry` and then we will c
Here, we will use the `readWKB` function from the `WKB` package to transform the `geometry`

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Spatial_Data_GBR_Features.Rmd
> +
Add here more info about the process of transforming the WKB geometry into an SF polygon object and the advantages of this object for plotting and filtering

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Spatial_Data_GBR_Features.Rmd
> +australia <- rnaturalearth::ne_countries(country = "Australia", returnclass = "sf")
here you assume that `rnaturalearth` package is available. Include it in the import packages section

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Spatial_Data_GBR_Features.Rmd
> +```
`library(rnaturalearth)`

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Spatial_Data_GBR_Features.Rmd
> +
Maybe adding some steps: 

1. Connect with RIMReP_DMS GBR features data collection and explore it
2. Get GBR features geometries
3. Convert WKB geometries into Simple Feature (sf) object
4. Export polygons as shapefiles

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +
This notebook uses a set of functions specially created for manipulating RIMReP data collections. The file `useful_spatial_functions_data_extraction.R` must exist in the same directory of this notebook

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +Connecting to the AIMS Sea Surface Temperature Monitoring Program. This can take a minute or so.
AIMS Sea Surface Temperature Monitoring Program dataset

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +                                          T ~ NA)) %>%
return "Other" instead of NA

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +  #Turning into shapefile
turning into a `sf` object

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +We will use the `gbr_features` function to access the boundaries for our sites of interest. If no parameters are given to this function, it will load all features recognised by the GBRMPA. You could
it will load all features recognised by ~the~ GBRMPA.

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +As an example, we will use **U/N Reef** or unnamed reefs. We chose them simply because they cover a large area and will overlap with the most number of AIMS monitoring sites.
In fact there are multiple reefs without a name, and they are referred to as **U/N Reef**, but each of them has a `UNIQUE_ID` value. The use of **U/N Reef** as a filter will return multiple reefs in the GBR

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +#Plotting results
How about plotting using Leafleat instead, so the user can zoom in/out the map

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +We will now extract data only for the monitoring sites located within the GBR feature of our interest.
This next step takes a lot of time to execute. Would it be better if you extract the sites of interest based on the previous step and then do the calculation locally?

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +ggsave(plot_out, temp_plot, device = "tiff")
maybe saving as png instead of tiff, it will take less space

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_at_Site.Rmd
> +This notebook will demonstrate how to access the RIMReP `geoparquet` collection for AIMS Sea Surface Temperature Monitoring Program. This dataset includes data since 1980 for tropical and subtropical
I think there are more than 80 sites, around 300. Check.

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_at_Site.Rmd
> +data_bucket <- s3_bucket("s3://rimrep-data-public/091-aims-sst/test-50-64-spatialpart")
Is this the correct bucket? Check with Leo

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_at_Site.Rmd
> +We can extract data from the AIMS dataset by using `dplyr` verbs as shown below.
We can extract location (coordinates) data from the AIMS dataset by using `dplyr` verbs as shown below.

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_at_Site.Rmd
> +                                          T ~ NA))
`Other` instead of `NA`

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_at_Site.Rmd
> +As explained [above](#exploring-dataset-structure), the `geometry` field is in WKB format, which we will transform into degree coordinates in the next step. Here, we will use the `WKB` to transform t
we will use the `readWKB` function from `WKB` package to transform the `geometry`

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_at_Site.Rmd
> +```
`library(rnaturalearth)`

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_at_Site.Rmd
> +Note that `qc_val` is the variable containing the temperature data in this dataset.
Note that `qc_val` is the variable containing quality-controlled temperature data in this dataset.

2023-06-13 02:53 UTC, diodon commented on poc-data-api/Extracting_Water_Temperature_at_Site.Rmd
> +sites_temp <- data_df %>%
This next step takes a lot of time to execute. Would it be better if you extract the sites of interest based on the previous step and then do the calculation locally?

2023-06-13 02:53 UTC, diodon commented on poc-data-api/useful_spatial_functions_data_extraction.R
> +# Useful functions to extract data using polygons
maybe documenting each function using `roxygen2`. But this is not a priority right now.

2023-06-13 03:50 UTC, lidefi87 commented on poc-data-api/Extracting_Spatial_Data_GBR_Features.Rmd
> +We can extract data from the AIMS dataset by using `dplyr` verbs as shown below.
Rephrased

2023-06-13 03:55 UTC, lidefi87 commented on poc-data-api/Extracting_Spatial_Data_GBR_Features.Rmd
> +australia <- rnaturalearth::ne_countries(country = "Australia", returnclass = "sf")
Added to list of imported packages

2023-06-13 04:11 UTC, lidefi87 commented on poc-data-api/Extracting_Spatial_Data_GBR_Features.Rmd
> +
added a new section (_workflow_) with these steps

2023-06-13 07:40 UTC, lidefi87 commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +
information added

2023-06-13 07:41 UTC, lidefi87 commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +                                          T ~ NA)) %>%
updated

2023-06-14 00:24 UTC, lidefi87 commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +#Plotting results
I added a `leaflet` map to the notebook. This way users can see how to produce an interactive and static map. We can remove the static version using `ggplot2` if you think is best

2023-06-14 00:46 UTC, lidefi87 commented on poc-data-api/Extracting_Water_Temperature_GBR_Features.Rmd
> +We will now extract data only for the monitoring sites located within the GBR feature of our interest.
I extracted the sites and then perform the calculations and it still takes some time, but it is less than the original version.

2023-06-14 01:32 UTC, lidefi87 commented on poc-data-api/Extracting_Water_Temperature_at_Site.Rmd
> +This notebook will demonstrate how to access the RIMReP `geoparquet` collection for AIMS Sea Surface Temperature Monitoring Program. This dataset includes data since 1980 for tropical and subtropical
This is my bad, I got this information from the [website](https://apps.aims.gov.au/metadata/view/4a12a8c0-c573-11dc-b99b-00008a07204e) describing the dataset and I did not actually check. A quick subset of the data using the maximum spatial extent gives me over 400 points. I have removed the number and rephrased this sentence.

2023-06-14 01:35 UTC, lidefi87 commented on poc-data-api/Extracting_Water_Temperature_at_Site.Rmd
> +data_bucket <- s3_bucket("s3://rimrep-data-public/091-aims-sst/test-50-64-spatialpart")
I checked in STAC and it shows the same URL.

2023-06-14 01:43 UTC, lidefi87 commented on poc-data-api/Extracting_Water_Temperature_at_Site.Rmd
> +sites_temp <- data_df %>%
It still takes some time, but I think it is slightly faster now

2023-06-14 01:47 UTC, lidefi87 commented on poc-data-api/useful_spatial_functions_data_extraction.R
> +# Useful functions to extract data using polygons
I have not used this library before, but I have been wanting to learn about it for a little while. Issue #8 opened. To be completed after notebooks are done.

2023-06-16 03:13 UTC, lidefi87 commented
@diodon final edits are now included in this pull request. Please let me know if you need any more changes.

2023-06-16 05:14 UTC, diodon approved these changes

2023-06-16 05:15 UTC, merged